### PR TITLE
1646683602 main make venv and activate

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
@bitkarrot - is there a violation of a standard (E999) or something concerning imports starting with an integer?
i.e. 0x20bf?

I looked it up but didn't see any restrictions on starting with a number.

**Comment by RandyMcMillan** [comment]
I would prefer to keep it 0x20bf.py - but I was getting a syntax error when it was named that. Could be me...but wanted to run it by you.

**Comment by bitkarrot** [comment]
Also see 

https://stackoverflow.com/questions/17487209/can-a-python-package-name-start-with-a-number

**Comment by bitkarrot** [comment]
I tested with upload to pypi, but when you install with `pip install 0x20bf` and then try `import 0x20bf` it gives a syntax error

**Pull request closed without merging**
