### PR TITLE
Lint python fix

### PR DESCRIPTION
**Pull request by bitkarrot**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
It is ok to be more granular in you commits. When re doing this PR - make every file its own commit.

**Comment by bitkarrot** [comment]
> It is ok to be more granular in your commits. When re doing this PR - make every file its own commit. This will allow me to use each commit individually as the shebangs are ok to strip. :)

OK as well as OK on iSort

> The other option is to remove GnuPG and p2p from the 0x20bf folder. but I would still want to keep our own copy in the repo. Maybe move them to the depends folder?
> #### Ideally this repo should be as autonomous as possible. Hosting our own critical dependancies in this repo.

YES ACK , move to depends folder.

**Comment by bitkarrot** [comment]
keeping this pull open a bit longer so i can review your notes

**Comment by RandyMcMillan** [comment]
I have started implementation of configsparser
if you start on an argsparser implementation - **be sure to rebase!**
We will want it to be able to commit user preferences to the 0x20bf/configs.ini file
that will exist in the next merge!

**Comment by RandyMcMillan** [comment]
My cadence is fast right now - it will certainly slow down once a few things are working.
Be sure to rebase your work regularly - I don't want you to work on a stale branch!

**Comment by bitkarrot** [comment]
> My cadence is fast right now - it will certainly slow down once a few things are working. Be sure to rebase your work regularly - I don't want you to work on a stale branch!

OK!

**Comment by bitkarrot** [comment]
ok starting argsparser implementation on another branch. feel free to merge this branch or close it if not needed.

**Pull request closed without merging**
