### PR TITLE
 use explicit for import not *

### PR DESCRIPTION
**Pull request by bitkarrot**
This is a work in progress. 

possibly see a circular import in "imports.py" where `from mempool_height import *` and "imports.py" is imported over other files.... not sure yet, still checking

### CODE REVIEW

**Comment by bitkarrot** [comment]
in twitter_api_keys.py i see access_token & secret and consumer api and secret. 

however when i go to twitter api and generate api keys for an app, i get apikey, api key secret and bearer token. 

can you explain which i should use for the above, where i only have 3 values and not 4? 

or am i missing something? @RandyMcMillan

**Comment by RandyMcMillan** [comment]
Checkout this branch:

I am adding a bunch of linting to the CI.

The witter thing is fixed in this branch.

I am almost finished with the CI linting.

https://github.com/RandyMcMillan/0x20bf/tree/1645996508-virtualenv-ci

**Comment by RandyMcMillan** [comment]
Let me get this to pass - then rebase on top of it...

https://github.com/RandyMcMillan/0x20bf/actions

**Comment by RandyMcMillan** [comment]
Sorry about the conflicts :(

**Comment by RandyMcMillan** [comment]
Rebase on top of my recent merge...

Something that you may be able to configure correctly is this---> https://github.com/0x20bf-org/0x20bf/blob/main/.github/workflows/virtualenv.yml#L30

If you turn this on - then let it run - you will see the issue.

There is some nuance to configuring this that I am not aware of - I suspect it is an easy fix for you! :)

**Comment by RandyMcMillan** [comment]
PS: 

you can see here --> https://github.com/0x20bf-org/0x20bf/blob/66409426c851ccbf0297212ac69f18a277b0a930/.github/workflows/virtualenv.yml#L32

that I kinda was hacky in my config of black... there is probably a proper way in the pyproject.toml 

I suspect you can fix this... 

Keep in mind that the CI is running `make install` this installs the contents of `requirements.txt`

**Comment by RandyMcMillan** [comment]
The TWEET flag is used to avoid the twitter api stuff

https://github.com/0x20bf-org/0x20bf/commit/d63a4a25bc8b7105d1f5c9b49f3dca372baa749b#diff-d5222d9d35b49e8b98448621626b201c56aa99bb106ccd3ac70e5d34baf10db9R43

I am in the middle of adding some secrets to the repo - keep in mind this is just part of my stuff for testing.
I will apply to twitter to get API keys for this app. Then we can integrate them for testing. :) 

NOTE: We will integrate "free" searches and such for the end user...

**Comment by RandyMcMillan** [comment]
I wish I had known about the `black` code formatter... this would have saved me a lot of time...

It was the last tool to configure in the CI

https://github.com/0x20bf-org/0x20bf/commit/d63a4a25bc8b7105d1f5c9b49f3dca372baa749b

:)

**Comment by bitkarrot** [comment]
Ok. btw, the imports.py file... should probably be renamed to something more appropriate, can get confusing with `from imports import X`

i can help fix this, will be back in a few hrs

**Comment by bitkarrot** [comment]
see: https://www.python.org/dev/peps/pep-0008/#imports

i'll look into the above issues as well :)

**Comment by bitkarrot** [comment]
> Sorry about the conflicts :(

no worries, i know we're building at breakneck, which is awesome and i will be happy to roll with the punches. 

still not entirely clear where the architecture is going, if you can say in a few words what is next, and how you want to roll in the other libs like p2p and gogs please let me know

**Comment by RandyMcMillan** [comment]
I see this...

**Comment by RandyMcMillan** [comment]
I merged a variation of this PR. fc4620d1cea798a8852070cf932c930a98512b71

**Pull request closed without merging**
