### PR TITLE
Add setup files for pip packaging

### PR DESCRIPTION
**Pull request by bitkarrot**
Starter files added
- had to rename directory to be same as package name to be released. 
- not sure about github actions impact? some were ok others not. 
- had to remove the symlink, feel free to put something else there

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
The conflicts are my fault...

I manually pulled in the changes from this PR (as you should see)
except for the README.md change

---

On your main branch:

git checkout -b readme-change
to save the readme change

git checkout main

then

git reset --hard 95c3554d2951f651cf59ab282aba3ca3814bd7c9

git pull upstream main

I can pull in that change today... just a bit tired... 

--- 

definitely work off of topic branches - keep main synced with upstream main

---

for a README.md change:

add the change to sources/FOOTER.md

then

make docs

git add sources index.html

git commit etc...


I use this in my git config:

```shell
git config --global pull.rebase true
git config pull.rebase true
```

this makes pull from upstream work - it works on topic branches too.

I will add a CONTRIBUTE file and we can document some of the work flow.

**Comment by RandyMcMillan** [comment]
PS: I added a p2p library - I tested an example in the venv - worked.

11711df1ef0409e5062429d761d89930af4ccff6

I don't believe the setup is placing the build in the correct place - if you can check that - that would be great.

I will look for a CI script to test a python3 venv configuration. 

👍🏽

**Comment by bitkarrot** [comment]
OK will do

**Comment by bitkarrot** [comment]
I made changes to fix setup build in this branch https://github.com/bitkarrot/0x20bf/tree/fix-setup

the p2p library looks interesting!

> PS: I added a p2p library - I tested an example in the venv - worked.
> 
> [11711df](https://github.com/0x20bf-org/0x20bf/commit/11711df1ef0409e5062429d761d89930af4ccff6)
> 
> I don't believe the setup is placing the build in the correct place - if you can check that - that would be great.
> 
> I will look for a CI script to test a python3 venv configuration.
> 
> 👍🏽

**Comment by bitkarrot** [comment]
conflicts should be fixed now.

**Pull request merged**
